package gov.ca.dir.acct.calosha.adf.usecase024.model.view.appmodule.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 07 23:11:31 PDT 2014
// ---------------------------------------------------------------------
public interface ReferralSearchInvoiceAM extends ApplicationModule {
    void doQueryResultReset();

    void refreshSearch();
}
