package gov.ca.dir.acct.calosha.adf.usecase024.model.view.appmodule.client;

import gov.ca.dir.acct.calosha.adf.usecase024.model.view.appmodule.common.ReferralSearchInvoiceAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 07 23:11:31 PDT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ReferralSearchInvoiceAMClient extends ApplicationModuleImpl implements ReferralSearchInvoiceAM {
    /**
     * This is the default constructor (do not remove).
     */
    public ReferralSearchInvoiceAMClient() {
    }

    public void doQueryResultReset() {
        Object _ret =
            this.riInvokeExportedMethod(this,"doQueryResultReset",null,null);
        return;
    }

    public void refreshSearch() {
        Object _ret = this.riInvokeExportedMethod(this,"refreshSearch",null,null);
        return;
    }
}
