package gov.ca.dir.acct.calosha.adf.usecase024.model.view.appmodule;

import gov.ca.dir.acct.calosha.adf.usecase024.model.view.appmodule.common.ReferralSearchInvoiceAM;

import oracle.jbo.ViewCriteria;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 07 15:29:09 PDT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ReferralSearchInvoiceAMImpl extends ApplicationModuleImpl implements ReferralSearchInvoiceAM {
    /**
     * This is the default constructor (do not remove).
     */
    public ReferralSearchInvoiceAMImpl() {
    }

    /**
     * Container's getter for InvoiceView1.
     * @return InvoiceView1
     */
    public ViewObjectImpl getInvoiceView1() {
        return (ViewObjectImpl)findViewObject("InvoiceView1");
    }

    /**
     * Container's getter for CitationItemView1.
     * @return CitationItemView1
     */
    public ViewObjectImpl getCitationItemView1() {
        return (ViewObjectImpl)findViewObject("CitationItemView1");
    }

    /**
     * Container's getter for CitationView1.
     * @return CitationView1
     */
    public ViewObjectImpl getCitationView1() {
        return (ViewObjectImpl)findViewObject("CitationView1");
    }

    /**
     * Container's getter for PersonView1.
     * @return PersonView1
     */
    public ViewObjectImpl getPersonView1() {
        return (ViewObjectImpl)findViewObject("PersonView1");
    }

    /**
     * Container's getter for SiteAddress.
     * @return SiteAddress
     */
    public ViewObjectImpl getSiteAddress() {
        return (ViewObjectImpl)findViewObject("SiteAddress");
    }

    /**
     * Container's getter for MailingAddress.
     * @return MailingAddress
     */
    public ViewObjectImpl getMailingAddress() {
        return (ViewObjectImpl)findViewObject("MailingAddress");
    }

    /**
     * Container's getter for AppealDetailView1.
     * @return AppealDetailView1
     */
    public ViewObjectImpl getAppealDetailView1() {
        return (ViewObjectImpl)findViewObject("AppealDetailView1");
    }

    /**
     * Container's getter for ContactMethodView1.
     * @return ContactMethodView1
     */
    public ViewObjectImpl getContactMethodView1() {
        return (ViewObjectImpl)findViewObject("ContactMethodView1");
    }

    /**
     * Container's getter for InvoiceAllPaymentView2.
     * @return InvoiceAllPaymentView2
     */
    public ViewObjectImpl getInvoiceAllPaymentView2() {
        return (ViewObjectImpl)findViewObject("InvoiceAllPaymentView2");
    }

    /**
     * Container's getter for JudgmentView1.
     * @return JudgmentView1
     */
    public ViewObjectImpl getJudgmentView1() {
        return (ViewObjectImpl)findViewObject("JudgmentView1");
    }

    /**
     * Container's getter for JudgmentDetailsView1.
     * @return JudgmentDetailsView1
     */
    public ViewObjectImpl getJudgmentDetailsView1() {
        return (ViewObjectImpl)findViewObject("JudgmentDetailsView1");
    }

    /**
     * Container's getter for PaymentPlanView1.
     * @return PaymentPlanView1
     */
    public ViewObjectImpl getPaymentPlanView1() {
        return (ViewObjectImpl)findViewObject("PaymentPlanView1");
    }

    /**
     * Container's getter for PaymentPlanDetailView1.
     * @return PaymentPlanDetailView1
     */
    public ViewObjectImpl getPaymentPlanDetailView1() {
        return (ViewObjectImpl)findViewObject("PaymentPlanDetailView1");
    }

    /**
     * Container's getter for OrganizaitonClassView1.
     * @return OrganizaitonClassView1
     */
    public ViewObjectImpl getOrganizaitonClassView1() {
        return (ViewObjectImpl)findViewObject("OrganizaitonClassView1");
    }

    /**
     * Container's getter for InvoiceCitationItemLink1.
     * @return InvoiceCitationItemLink1
     */
    public ViewLinkImpl getInvoiceCitationItemLink1() {
        return (ViewLinkImpl)findViewLink("InvoiceCitationItemLink1");
    }

    /**
     * Container's getter for InvoiceCitationLink1.
     * @return InvoiceCitationLink1
     */
    public ViewLinkImpl getInvoiceCitationLink1() {
        return (ViewLinkImpl)findViewLink("InvoiceCitationLink1");
    }

    /**
     * Container's getter for InvoicePersonLink1.
     * @return InvoicePersonLink1
     */
    public ViewLinkImpl getInvoicePersonLink1() {
        return (ViewLinkImpl)findViewLink("InvoicePersonLink1");
    }

    /**
     * Container's getter for InvoiceAddressLink1.
     * @return InvoiceAddressLink1
     */
    public ViewLinkImpl getInvoiceAddressLink1() {
        return (ViewLinkImpl)findViewLink("InvoiceAddressLink1");
    }

    /**
     * Container's getter for InvoiceAddressLink2.
     * @return InvoiceAddressLink2
     */
    public ViewLinkImpl getInvoiceAddressLink2() {
        return (ViewLinkImpl)findViewLink("InvoiceAddressLink2");
    }

    /**
     * Container's getter for InvoiceAppealDetailLink1.
     * @return InvoiceAppealDetailLink1
     */
    public ViewLinkImpl getInvoiceAppealDetailLink1() {
        return (ViewLinkImpl)findViewLink("InvoiceAppealDetailLink1");
    }

    /**
     * Container's getter for InvoiceContactMethodLink1.
     * @return InvoiceContactMethodLink1
     */
    public ViewLinkImpl getInvoiceContactMethodLink1() {
        return (ViewLinkImpl)findViewLink("InvoiceContactMethodLink1");
    }

    /**
     * Container's getter for InvoicePaymentLink1.
     * @return InvoicePaymentLink1
     */
    public ViewLinkImpl getInvoicePaymentLink1() {
        return (ViewLinkImpl)findViewLink("InvoicePaymentLink1");
    }

    /**
     * Container's getter for InvoiceJudgmentLink1.
     * @return InvoiceJudgmentLink1
     */
    public ViewLinkImpl getInvoiceJudgmentLink1() {
        return (ViewLinkImpl)findViewLink("InvoiceJudgmentLink1");
    }

    /**
     * Container's getter for JudgmentJudgmentDetailLink1.
     * @return JudgmentJudgmentDetailLink1
     */
    public ViewLinkImpl getJudgmentJudgmentDetailLink1() {
        return (ViewLinkImpl)findViewLink("JudgmentJudgmentDetailLink1");
    }

    /**
     * Container's getter for InvoicePaymentPlanLink1.
     * @return InvoicePaymentPlanLink1
     */
    public ViewLinkImpl getInvoicePaymentPlanLink1() {
        return (ViewLinkImpl)findViewLink("InvoicePaymentPlanLink1");
    }

    /**
     * Container's getter for PaymentPlanDetailLink1.
     * @return PaymentPlanDetailLink1
     */
    public ViewLinkImpl getPaymentPlanDetailLink1() {
        return (ViewLinkImpl)findViewLink("PaymentPlanDetailLink1");
    }

    /**
     * Container's getter for InvoiceOrganizationViewLink1.
     * @return InvoiceOrganizationViewLink1
     */
    public ViewLinkImpl getInvoiceOrganizationViewLink1() {
        return (ViewLinkImpl)findViewLink("InvoiceOrganizationViewLink1");
    }

    /*Vinay Patil: Custom method to clear the query results from the View Criteria in the Query Panel*/
    public void doQueryResultReset() {
        String VOCriteria = "SearchInvoiceCriteria";
        
        ViewCriteria vc = this.getInvoiceView1().getViewCriteria(VOCriteria); 

        System.out.println("Empty table data for the View Criteria ="+VOCriteria+ " vc = "+vc);
        
        this.getInvoiceView1().removeViewCriteria(VOCriteria);
        this.getInvoiceView1().executeEmptyRowSet();
        this.getInvoiceView1().applyViewCriteria(vc);
    }    

    public void refreshSearch() {
        String VOCriteria = "SearchInvoiceCriteria";
        
        ViewCriteria vc = this.getInvoiceView1().getViewCriteria(VOCriteria); 
        System.out.println("Refresh page with same search criteria of the View Criteria ="+VOCriteria+ " vc = "+vc);

        this.getInvoiceView1().executeQuery();

    }


    /**
     * Container's getter for ReportingtoIndexMapView1.
     * @return ReportingtoIndexMapView1
     */
    public ViewObjectImpl getReportingtoIndexMapView1() {
        return (ViewObjectImpl)findViewObject("ReportingtoIndexMapView1");
    }

    /**
     * Container's getter for InvoiceReportingToIndexMapViewLink1.
     * @return InvoiceReportingToIndexMapViewLink1
     */
    public ViewLinkImpl getInvoiceReportingToIndexMapViewLink1() {
        return (ViewLinkImpl)findViewLink("InvoiceReportingToIndexMapViewLink1");
    }


    /**
     * Container's getter for ReferralView1.
     * @return ReferralView1
     */
    public ViewObjectImpl getReferralView1() {
        return (ViewObjectImpl)findViewObject("ReferralView1");
    }

    /**
     * Container's getter for InvoiceReferralLink1.
     * @return InvoiceReferralLink1
     */
    public ViewLinkImpl getInvoiceReferralLink1() {
        return (ViewLinkImpl)findViewLink("InvoiceReferralLink1");
    }


    /**
     * Container's getter for ContactPhoneView1.
     * @return ContactPhoneView1
     */
    public ViewObjectImpl getContactPhoneView1() {
        return (ViewObjectImpl)findViewObject("ContactPhoneView1");
    }

    /**
     * Container's getter for InvoiceContactMethodLink2.
     * @return InvoiceContactMethodLink2
     */
    public ViewLinkImpl getInvoiceContactMethodLink2() {
        return (ViewLinkImpl)findViewLink("InvoiceContactMethodLink2");
    }


    /**
     * Container's getter for ThirdPartyCollectionNView2.
     * @return ThirdPartyCollectionNView2
     */
    public ViewObjectImpl getThirdPartyCollectionValidNRView() {
        return (ViewObjectImpl)findViewObject("ThirdPartyCollectionValidNRView");
    }

    /**
     * Container's getter for InvoiceThirdPartyCollectionNViewLink1.
     * @return InvoiceThirdPartyCollectionNViewLink1
     */
    public ViewLinkImpl getInvoiceThirdPartyCollectionNViewLink1() {
        return (ViewLinkImpl)findViewLink("InvoiceThirdPartyCollectionNViewLink1");
    }


    /**
     * Container's getter for ThirdPartyCollectionDView2.
     * @return ThirdPartyCollectionDView2
     */
    public ViewObjectImpl getThirdPartyCollectionDView2() {
        return (ViewObjectImpl)findViewObject("ThirdPartyCollectionDView2");
    }

    /**
     * Container's getter for ThirdPartyCollectionNView2.
     * @return ThirdPartyCollectionNView2
     */
    public ViewObjectImpl getThirdPartyCollectionNView2() {
        return (ViewObjectImpl)findViewObject("ThirdPartyCollectionNView2");
    }

    /**
     * Container's getter for ThirdPartyCollectionHeaderView2.
     * @return ThirdPartyCollectionHeaderView2
     */
    public ViewObjectImpl getThirdPartyCollectionHeaderView2() {
        return (ViewObjectImpl)findViewObject("ThirdPartyCollectionHeaderView2");
    }

    /**
     * Container's getter for PartyClassificationView1.
     * @return PartyClassificationView1
     */
    public ViewObjectImpl getPartyClassificationView1() {
        return (ViewObjectImpl)findViewObject("PartyClassificationView1");
    }

    /**
     * Container's getter for InvoicePartyClassificationLink1.
     * @return InvoicePartyClassificationLink1
     */
    public ViewLinkImpl getInvoicePartyClassificationLink1() {
        return (ViewLinkImpl)findViewLink("InvoicePartyClassificationLink1");
    }

    /**
     * Container's getter for ThirdPartyCollAssocView1.
     * @return ThirdPartyCollAssocView1
     */
    public ViewObjectImpl getThirdPartyCollAssocView1() {
        return (ViewObjectImpl)findViewObject("ThirdPartyCollAssocView1");
    }

    /**
     * Container's getter for ThirdPartyCollectionPCView1.
     * @return ThirdPartyCollectionPCView1
     */
    public ViewObjectImpl getThirdPartyCollectionPCView1() {
        return (ViewObjectImpl)findViewObject("ThirdPartyCollectionPCView1");
    }

    /**
     * Container's getter for ThirdPartyCollectionOView1.
     * @return ThirdPartyCollectionOView1
     */
    public ViewObjectImpl getThirdPartyCollectionOView1() {
        return (ViewObjectImpl)findViewObject("ThirdPartyCollectionOView1");
    }

    /**
     * Container's getter for ThirdPartyCollAssocView2.
     * @return ThirdPartyCollAssocView2
     */
    public ViewObjectImpl getThirdPartyCollAssocView2() {
        return (ViewObjectImpl)findViewObject("ThirdPartyCollAssocView2");
    }

    /**
     * Container's getter for TpcOToTpcAssocViewLink1.
     * @return TpcOToTpcAssocViewLink1
     */
    public ViewLinkImpl getTpcOToTpcAssocViewLink1() {
        return (ViewLinkImpl)findViewLink("TpcOToTpcAssocViewLink1");
    }

    /**
     * Container's getter for ThirdPartyCollAssocView3.
     * @return ThirdPartyCollAssocView3
     */
    public ViewObjectImpl getThirdPartyCollAssocView3() {
        return (ViewObjectImpl)findViewObject("ThirdPartyCollAssocView3");
    }

    /**
     * Container's getter for TpcDToTpcAssocViewLink1.
     * @return TpcDToTpcAssocViewLink1
     */
    public ViewLinkImpl getTpcDToTpcAssocViewLink1() {
        return (ViewLinkImpl)findViewLink("TpcDToTpcAssocViewLink1");
    }

    /**
     * Container's getter for ThirdPartyCollAssocView4.
     * @return ThirdPartyCollAssocView4
     */
    public ViewObjectImpl getThirdPartyCollAssocView4() {
        return (ViewObjectImpl)findViewObject("ThirdPartyCollAssocView4");
    }

    /**
     * Container's getter for TpcPToTpcAssocViewLink1.
     * @return TpcPToTpcAssocViewLink1
     */
    public ViewLinkImpl getTpcPToTpcAssocViewLink1() {
        return (ViewLinkImpl)findViewLink("TpcPToTpcAssocViewLink1");
    }

    /**
     * Container's getter for ThirdPartyCollAssocView5.
     * @return ThirdPartyCollAssocView5
     */
    public ViewObjectImpl getThirdPartyCollAssocView5() {
        return (ViewObjectImpl)findViewObject("ThirdPartyCollAssocView5");
    }

    /**
     * Container's getter for TpcRToTpcAssocViewLink1.
     * @return TpcRToTpcAssocViewLink1
     */
    public ViewLinkImpl getTpcRToTpcAssocViewLink1() {
        return (ViewLinkImpl)findViewLink("TpcRToTpcAssocViewLink1");
    }


    /**
     * Container's getter for ThirdPartyCollectionHeaderView1.
     * @return ThirdPartyCollectionHeaderView1
     */
    public ViewObjectImpl getThirdPartyCollectionHeaderView1() {
        return (ViewObjectImpl)findViewObject("ThirdPartyCollectionHeaderView1");
    }

    /**
     * Container's getter for ThirdPartyCollectionAnyView1.
     * @return ThirdPartyCollectionAnyView1
     */
    public ViewObjectImpl getThirdPartyCollectionAnyView1() {
        return (ViewObjectImpl)findViewObject("ThirdPartyCollectionAnyView1");
    }

    /**
     * Container's getter for ThirdPartyCollAssocView6.
     * @return ThirdPartyCollAssocView6
     */
    public ViewObjectImpl getThirdPartyCollAssocView6() {
        return (ViewObjectImpl)findViewObject("ThirdPartyCollAssocView6");
    }

    /**
     * Container's getter for TpcChildrenToTpcNAssocViewLink1.
     * @return TpcChildrenToTpcNAssocViewLink1
     */
    public ViewLinkImpl getTpcChildrenToTpcNAssocViewLink1() {
        return (ViewLinkImpl)findViewLink("TpcChildrenToTpcNAssocViewLink1");
    }

    /**
     * Container's getter for FeeView1.
     * @return FeeView1
     */
    public ViewObjectImpl getFeeView1() {
        return (ViewObjectImpl)findViewObject("FeeView1");
    }


    /**
     * Container's getter for RelatedPartyView1.
     * @return RelatedPartyView1
     */
    public ViewObjectImpl getRelatedPartyView1() {
        return (ViewObjectImpl)findViewObject("RelatedPartyView1");
    }

    /**
     * Container's getter for PersonView2.
     * @return PersonView2
     */
    public ViewObjectImpl getPersonView2() {
        return (ViewObjectImpl)findViewObject("PersonView2");
    }

    /**
     * Container's getter for PartyView1.
     * @return PartyView1
     */
    public ViewObjectImpl getPartyView1() {
        return (ViewObjectImpl)findViewObject("PartyView1");
    }

    /**
     * Container's getter for OrganizationView1.
     * @return OrganizationView1
     */
    public ViewObjectImpl getOrganizationView1() {
        return (ViewObjectImpl)findViewObject("OrganizationView1");
    }

    /**
     * Container's getter for CallLogView1.
     * @return CallLogView1
     */
    public ViewObjectImpl getCallLogView1() {
        return (ViewObjectImpl)findViewObject("CallLogView1");
    }

    /**
     * Container's getter for InvoiceViewCallLogViewLink1.
     * @return InvoiceViewCallLogViewLink1
     */
    public ViewLinkImpl getInvoiceViewCallLogViewLink1() {
        return (ViewLinkImpl)findViewLink("InvoiceViewCallLogViewLink1");
    }

    /**
     * Container's getter for ValidJudgmentView.
     * @return ValidJudgmentView
     */
    public ViewObjectImpl getValidJudgmentView() {
        return (ViewObjectImpl)findViewObject("ValidJudgmentView");
    }

    /**
     * Container's getter for InvoiceJudgmentLink2.
     * @return InvoiceJudgmentLink2
     */
    public ViewLinkImpl getInvoiceJudgmentLink2() {
        return (ViewLinkImpl)findViewLink("InvoiceJudgmentLink2");
    }

    /**
     * Container's getter for CoeRequestView1.
     * @return CoeRequestView1
     */
    public ViewObjectImpl getValidCoeRequestView() {
        return (ViewObjectImpl)findViewObject("ValidCoeRequestView");
    }

    /**
     * Container's getter for InvoiceCoeRequestLink1.
     * @return InvoiceCoeRequestLink1
     */
    public ViewLinkImpl getInvoiceCoeRequestLink1() {
        return (ViewLinkImpl)findViewLink("InvoiceCoeRequestLink1");
    }

    /**
     * Container's getter for DelinquentPayPlan.
     * @return DelinquentPayPlan
     */
    public ViewObjectImpl getDelinquentPayPlanView() {
        return (ViewObjectImpl)findViewObject("DelinquentPayPlanView");
    }

    /**
     * Container's getter for InvoicePaymentPlanLink2.
     * @return InvoicePaymentPlanLink2
     */
    public ViewLinkImpl getInvoicePaymentPlanLink2() {
        return (ViewLinkImpl)findViewLink("InvoicePaymentPlanLink2");
    }

    /**
     * Container's getter for PaymentPlanView2.
     * @return PaymentPlanView2
     */
    public ViewObjectImpl getValidPaymentPlanView() {
        return (ViewObjectImpl)findViewObject("ValidPaymentPlanView");
    }

    /**
     * Container's getter for InvoicePaymentPlanLink3.
     * @return InvoicePaymentPlanLink3
     */
    public ViewLinkImpl getInvoicePaymentPlanLink3() {
        return (ViewLinkImpl)findViewLink("InvoicePaymentPlanLink3");
    }

    /**
     * Container's getter for RelatedPartyView2.
     * @return RelatedPartyView2
     */
    public ViewObjectImpl getCollectionStaffPartyIdView() {
        return (ViewObjectImpl)findViewObject("CollectionStaffPartyIdView");
    }

    /**
     * Container's getter for RelatedPartyCollectionStaffInvoiceViewLink1.
     * @return RelatedPartyCollectionStaffInvoiceViewLink1
     */
    public ViewLinkImpl getRelatedPartyCollectionStaffInvoiceViewLink1() {
        return (ViewLinkImpl)findViewLink("RelatedPartyCollectionStaffInvoiceViewLink1");
    }


    /**
     * Container's getter for ThirdPartyCollectionLastNRCeasedRecall.
     * @return ThirdPartyCollectionLastNRCeasedRecall
     */
    public ViewObjectImpl getThirdPartyCollectionLastNRCeasedRecall() {
        return (ViewObjectImpl)findViewObject("ThirdPartyCollectionLastNRCeasedRecall");
    }

    /**
     * Container's getter for InvoiceThirdPartyCollectionNViewLink2.
     * @return InvoiceThirdPartyCollectionNViewLink2
     */
    public ViewLinkImpl getInvoiceThirdPartyCollectionNViewLink2() {
        return (ViewLinkImpl)findViewLink("InvoiceThirdPartyCollectionNViewLink2");
    }
}
