package gov.ca.dir.acct.calosha.adf.usecase001.model.view;

import oracle.jbo.Row;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 21 14:36:32 PDT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SiteAddressViewRowImpl extends ViewRowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SiteAddressViewRowImpl() {
    }

    /**
     * Gets Address entity object.
     * @return the Address
     */
    public EntityImpl getAddress() {
        return (EntityImpl)getEntity(0);
    }
    @Override
    public void setNewRowState(byte state) {
        if (state != Row.STATUS_INITIALIZED || getNewRowState() != Row.STATUS_NEW)
        { super.setNewRowState(state); }
        }
    
    public Number getSequenceNumber(String sequenceName){
        Number sequenceValue = new Number(0);
        if (sequenceName != null && ! sequenceName.isEmpty()){
            
            SequenceImpl sequenceImpl = new SequenceImpl(sequenceName,getDBTransaction());
            sequenceValue = sequenceImpl.getSequenceNumber();
            }
        return sequenceValue;
    }
}
