package gov.ca.dir.acct.calosha.adf.usecase024.model.view;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 07 14:17:20 PDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ThirdPartyCollectionNViewRowImpl extends ViewRowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ThirdPartyCollectionNViewRowImpl() {
    }

    /**
     * Gets ThirdPartyCollection entity object.
     * @return the ThirdPartyCollection
     */
    public EntityImpl getThirdPartyCollection() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets ThirdPartyCollAssoc entity object.
     * @return the ThirdPartyCollAssoc
     */
    public EntityImpl getTpcAssoc() {
        return (EntityImpl)getEntity(1);
    }

    /**
     * Gets ThirdPartyCollection1 entity object.
     * @return the ThirdPartyCollection1
     */
    public EntityImpl getTpcAssocToTpc() {
        return (EntityImpl)getEntity(2);
    }

    /**
     * Gets ThirdPartyCollectHeader entity object.
     * @return the ThirdPartyCollectHeader
     */
    public EntityImpl getThirdPartyCollectHeader() {
        return (EntityImpl)getEntity(3);
    }

    public Number getSequenceNumber(String sequenceName) {
        Number sequenceValue = new Number(0);
        if (sequenceName != null && !sequenceName.isEmpty()) {

            SequenceImpl sequenceImpl =
                new SequenceImpl(sequenceName, getDBTransaction());
            sequenceValue = sequenceImpl.getSequenceNumber();
        }
        return sequenceValue;
    }
}
