package gov.ca.dir.acct.calosha.adf.usecase0102.model.view;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 09 09:06:41 PDT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PaymentPlanAllocationViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Comments {
            public Object get(PaymentPlanAllocationViewRowImpl obj) {
                return obj.getComments();
            }

            public void put(PaymentPlanAllocationViewRowImpl obj,
                            Object value) {
                obj.setComments((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(PaymentPlanAllocationViewRowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(PaymentPlanAllocationViewRowImpl obj,
                            Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreatedDate {
            public Object get(PaymentPlanAllocationViewRowImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(PaymentPlanAllocationViewRowImpl obj,
                            Object value) {
                obj.setCreatedDate((Date)value);
            }
        }
        ,
        DataSourceCode {
            public Object get(PaymentPlanAllocationViewRowImpl obj) {
                return obj.getDataSourceCode();
            }

            public void put(PaymentPlanAllocationViewRowImpl obj,
                            Object value) {
                obj.setDataSourceCode((String)value);
            }
        }
        ,
        ModifiedBy {
            public Object get(PaymentPlanAllocationViewRowImpl obj) {
                return obj.getModifiedBy();
            }

            public void put(PaymentPlanAllocationViewRowImpl obj,
                            Object value) {
                obj.setModifiedBy((String)value);
            }
        }
        ,
        ModifiedDate {
            public Object get(PaymentPlanAllocationViewRowImpl obj) {
                return obj.getModifiedDate();
            }

            public void put(PaymentPlanAllocationViewRowImpl obj,
                            Object value) {
                obj.setModifiedDate((Date)value);
            }
        }
        ,
        PaymentAllocationId {
            public Object get(PaymentPlanAllocationViewRowImpl obj) {
                return obj.getPaymentAllocationId();
            }

            public void put(PaymentPlanAllocationViewRowImpl obj,
                            Object value) {
                obj.setPaymentAllocationId((Number)value);
            }
        }
        ,
        PaymentPlanDetailId {
            public Object get(PaymentPlanAllocationViewRowImpl obj) {
                return obj.getPaymentPlanDetailId();
            }

            public void put(PaymentPlanAllocationViewRowImpl obj,
                            Object value) {
                obj.setPaymentPlanDetailId((Number)value);
            }
        }
        ,
        Status {
            public Object get(PaymentPlanAllocationViewRowImpl obj) {
                return obj.getStatus();
            }

            public void put(PaymentPlanAllocationViewRowImpl obj,
                            Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        PaymentPlanAllocationId {
            public Object get(PaymentPlanAllocationViewRowImpl obj) {
                return obj.getPaymentPlanAllocationId();
            }

            public void put(PaymentPlanAllocationViewRowImpl obj,
                            Object value) {
                obj.setPaymentPlanAllocationId((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PaymentPlanAllocationViewRowImpl object);

        public abstract void put(PaymentPlanAllocationViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int DATASOURCECODE = AttributesEnum.DataSourceCode.index();
    public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int PAYMENTALLOCATIONID = AttributesEnum.PaymentAllocationId.index();
    public static final int PAYMENTPLANDETAILID = AttributesEnum.PaymentPlanDetailId.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int PAYMENTPLANALLOCATIONID = AttributesEnum.PaymentPlanAllocationId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PaymentPlanAllocationViewRowImpl() {
    }

    /**
     * Gets PaymentPlanAllocation entity object.
     * @return the PaymentPlanAllocation
     */
    public EntityImpl getPaymentPlanAllocation() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for COMMENTS using the alias name Comments.
     * @return the COMMENTS
     */
    public String getComments() {
        return (String) getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMENTS using the alias name Comments.
     * @param value value to set the COMMENTS
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for DATA_SOURCE_CODE using the alias name DataSourceCode.
     * @return the DATA_SOURCE_CODE
     */
    public String getDataSourceCode() {
        return (String) getAttributeInternal(DATASOURCECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for DATA_SOURCE_CODE using the alias name DataSourceCode.
     * @param value value to set the DATA_SOURCE_CODE
     */
    public void setDataSourceCode(String value) {
        setAttributeInternal(DATASOURCECODE, value);
    }

    /**
     * Gets the attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @return the MODIFIED_BY
     */
    public String getModifiedBy() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @param value value to set the MODIFIED_BY
     */
    public void setModifiedBy(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @return the MODIFIED_DATE
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @param value value to set the MODIFIED_DATE
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for PAYMENT_ALLOCATION_ID using the alias name PaymentAllocationId.
     * @return the PAYMENT_ALLOCATION_ID
     */
    public Number getPaymentAllocationId() {
        return (Number) getAttributeInternal(PAYMENTALLOCATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYMENT_ALLOCATION_ID using the alias name PaymentAllocationId.
     * @param value value to set the PAYMENT_ALLOCATION_ID
     */
    public void setPaymentAllocationId(Number value) {
        setAttributeInternal(PAYMENTALLOCATIONID, value);
    }

    /**
     * Gets the attribute value for PAYMENT_PLAN_DETAIL_ID using the alias name PaymentPlanDetailId.
     * @return the PAYMENT_PLAN_DETAIL_ID
     */
    public Number getPaymentPlanDetailId() {
        return (Number) getAttributeInternal(PAYMENTPLANDETAILID);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYMENT_PLAN_DETAIL_ID using the alias name PaymentPlanDetailId.
     * @param value value to set the PAYMENT_PLAN_DETAIL_ID
     */
    public void setPaymentPlanDetailId(Number value) {
        setAttributeInternal(PAYMENTPLANDETAILID, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for PAYMENT_PLAN_ALLOCATION_ID using the alias name PaymentPlanAllocationId.
     * @return the PAYMENT_PLAN_ALLOCATION_ID
     */
    public Number getPaymentPlanAllocationId() {
        return (Number) getAttributeInternal(PAYMENTPLANALLOCATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYMENT_PLAN_ALLOCATION_ID using the alias name PaymentPlanAllocationId.
     * @param value value to set the PAYMENT_PLAN_ALLOCATION_ID
     */
    public void setPaymentPlanAllocationId(Number value) {
        setAttributeInternal(PAYMENTPLANALLOCATIONID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
    
    public Number getSequenceNumber(String sequenceName){
        Number sequenceValue = new Number(0);
        if (sequenceName != null && ! sequenceName.isEmpty()){
            
            SequenceImpl sequenceImpl = new SequenceImpl(sequenceName,getDBTransaction());
            sequenceValue = sequenceImpl.getSequenceNumber();
            }
        return sequenceValue;
        }
}
