package gov.ca.dir.acct.calosha.adf.usecase001.model.appmodule;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 21 09:20:22 PDT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployerSearchAMImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployerSearchAMImpl() {
    }

    /**
     * Container's getter for EmployerSearchView1.
     * @return EmployerSearchView1
     */
    public ViewObjectImpl getEmployerSearchView1() {
        return (ViewObjectImpl)findViewObject("EmployerSearchView1");
    }

    /**
     * Container's getter for PartyView1.
     * @return PartyView1
     */
    public ViewObjectImpl getPartyView1() {
        return (ViewObjectImpl)findViewObject("PartyView1");
    }

    /**
     * Container's getter for AddressView1.
     * @return AddressView1
     */
    public ViewObjectImpl getAddressView1() {
        return (ViewObjectImpl)findViewObject("AddressView1");
    }

    /**
     * Container's getter for CellphoneView1.
     * @return CellphoneView1
     */
    public ViewObjectImpl getCellphoneView1() {
        return (ViewObjectImpl)findViewObject("CellphoneView1");
    }

    /**
     * Container's getter for EmailView1.
     * @return EmailView1
     */
    public ViewObjectImpl getEmailView1() {
        return (ViewObjectImpl)findViewObject("EmailView1");
    }

    /**
     * Container's getter for FaxView1.
     * @return FaxView1
     */
    public ViewObjectImpl getFaxView1() {
        return (ViewObjectImpl)findViewObject("FaxView1");
    }

    /**
     * Container's getter for PhoneView1.
     * @return PhoneView1
     */
    public ViewObjectImpl getPhoneView1() {
        return (ViewObjectImpl)findViewObject("PhoneView1");
    }

    /**
     * Container's getter for UrlView1.
     * @return UrlView1
     */
    public ViewObjectImpl getUrlView1() {
        return (ViewObjectImpl)findViewObject("UrlView1");
    }

    /**
     * Container's getter for Website_View1.
     * @return Website_View1
     */
    public ViewObjectImpl getWebsite_View1() {
        return (ViewObjectImpl)findViewObject("Website_View1");
    }

    /**
     * Container's getter for WorkphoneView1.
     * @return WorkphoneView1
     */
    public ViewObjectImpl getWorkphoneView1() {
        return (ViewObjectImpl)findViewObject("WorkphoneView1");
    }

    /**
     * Container's getter for UpdateEmployerView1.
     * @return UpdateEmployerView1
     */
    public ViewObjectImpl getUpdateEmployerView1() {
        return (ViewObjectImpl)findViewObject("UpdateEmployerView1");
    }

    /**
     * Container's getter for AddressView2.
     * @return AddressView2
     */
    public ViewObjectImpl getAddressView2() {
        return (ViewObjectImpl)findViewObject("AddressView2");
    }

    /**
     * Container's getter for CellphoneView2.
     * @return CellphoneView2
     */
    public ViewObjectImpl getCellphoneView2() {
        return (ViewObjectImpl)findViewObject("CellphoneView2");
    }

    /**
     * Container's getter for EmailView2.
     * @return EmailView2
     */
    public ViewObjectImpl getEmailView2() {
        return (ViewObjectImpl)findViewObject("EmailView2");
    }

    /**
     * Container's getter for FaxView2.
     * @return FaxView2
     */
    public ViewObjectImpl getFaxView2() {
        return (ViewObjectImpl)findViewObject("FaxView2");
    }

    /**
     * Container's getter for OrganizationView1.
     * @return OrganizationView1
     */
    public ViewObjectImpl getOrganizationView1() {
        return (ViewObjectImpl)findViewObject("OrganizationView1");
    }

    /**
     * Container's getter for PhoneView2.
     * @return PhoneView2
     */
    public ViewObjectImpl getPhoneView2() {
        return (ViewObjectImpl)findViewObject("PhoneView2");
    }

    /**
     * Container's getter for UrlView2.
     * @return UrlView2
     */
    public ViewObjectImpl getUrlView2() {
        return (ViewObjectImpl)findViewObject("UrlView2");
    }

    /**
     * Container's getter for Website_View2.
     * @return Website_View2
     */
    public ViewObjectImpl getWebsite_View2() {
        return (ViewObjectImpl)findViewObject("Website_View2");
    }

    /**
     * Container's getter for WorkphoneView2.
     * @return WorkphoneView2
     */
    public ViewObjectImpl getWorkphoneView2() {
        return (ViewObjectImpl)findViewObject("WorkphoneView2");
    }

    /**
     * Container's getter for OrganizationView2.
     * @return OrganizationView2
     */
    public ViewObjectImpl getOrganizationView2() {
        return (ViewObjectImpl)findViewObject("OrganizationView2");
    }


    /**
     * Container's getter for PartyAddressLink1.
     * @return PartyAddressLink1
     */
    public ViewLinkImpl getPartyAddressLink1() {
        return (ViewLinkImpl)findViewLink("PartyAddressLink1");
    }

    /**
     * Container's getter for PartyCellphoneLink1.
     * @return PartyCellphoneLink1
     */
    public ViewLinkImpl getPartyCellphoneLink1() {
        return (ViewLinkImpl)findViewLink("PartyCellphoneLink1");
    }

    /**
     * Container's getter for PartyEmailLink1.
     * @return PartyEmailLink1
     */
    public ViewLinkImpl getPartyEmailLink1() {
        return (ViewLinkImpl)findViewLink("PartyEmailLink1");
    }

    /**
     * Container's getter for PartyFaxLink1.
     * @return PartyFaxLink1
     */
    public ViewLinkImpl getPartyFaxLink1() {
        return (ViewLinkImpl)findViewLink("PartyFaxLink1");
    }

    /**
     * Container's getter for PartyPhoneLink1.
     * @return PartyPhoneLink1
     */
    public ViewLinkImpl getPartyPhoneLink1() {
        return (ViewLinkImpl)findViewLink("PartyPhoneLink1");
    }

    /**
     * Container's getter for PartyUrlLink1.
     * @return PartyUrlLink1
     */
    public ViewLinkImpl getPartyUrlLink1() {
        return (ViewLinkImpl)findViewLink("PartyUrlLink1");
    }

    /**
     * Container's getter for PartyWebsiteLink1.
     * @return PartyWebsiteLink1
     */
    public ViewLinkImpl getPartyWebsiteLink1() {
        return (ViewLinkImpl)findViewLink("PartyWebsiteLink1");
    }

    /**
     * Container's getter for PartyWorkphoneLink1.
     * @return PartyWorkphoneLink1
     */
    public ViewLinkImpl getPartyWorkphoneLink1() {
        return (ViewLinkImpl)findViewLink("PartyWorkphoneLink1");
    }

    /**
     * Container's getter for EmployerSearchViewPartyLink1.
     * @return EmployerSearchViewPartyLink1
     */
    public ViewLinkImpl getEmployerSearchViewPartyLink1() {
        return (ViewLinkImpl)findViewLink("EmployerSearchViewPartyLink1");
    }

    /**
     * Container's getter for PartyAddressLink2.
     * @return PartyAddressLink2
     */
    public ViewLinkImpl getPartyAddressLink2() {
        return (ViewLinkImpl)findViewLink("PartyAddressLink2");
    }

    /**
     * Container's getter for PartyCellphoneLink2.
     * @return PartyCellphoneLink2
     */
    public ViewLinkImpl getPartyCellphoneLink2() {
        return (ViewLinkImpl)findViewLink("PartyCellphoneLink2");
    }

    /**
     * Container's getter for PartyEmailLink2.
     * @return PartyEmailLink2
     */
    public ViewLinkImpl getPartyEmailLink2() {
        return (ViewLinkImpl)findViewLink("PartyEmailLink2");
    }

    /**
     * Container's getter for PartyFaxLink2.
     * @return PartyFaxLink2
     */
    public ViewLinkImpl getPartyFaxLink2() {
        return (ViewLinkImpl)findViewLink("PartyFaxLink2");
    }

    /**
     * Container's getter for PartyOrganizationLink1.
     * @return PartyOrganizationLink1
     */
    public ViewLinkImpl getPartyOrganizationLink1() {
        return (ViewLinkImpl)findViewLink("PartyOrganizationLink1");
    }

    /**
     * Container's getter for PartyPhoneLink2.
     * @return PartyPhoneLink2
     */
    public ViewLinkImpl getPartyPhoneLink2() {
        return (ViewLinkImpl)findViewLink("PartyPhoneLink2");
    }

    /**
     * Container's getter for PartyUrlLink2.
     * @return PartyUrlLink2
     */
    public ViewLinkImpl getPartyUrlLink2() {
        return (ViewLinkImpl)findViewLink("PartyUrlLink2");
    }

    /**
     * Container's getter for PartyWebsiteLink2.
     * @return PartyWebsiteLink2
     */
    public ViewLinkImpl getPartyWebsiteLink2() {
        return (ViewLinkImpl)findViewLink("PartyWebsiteLink2");
    }

    /**
     * Container's getter for PartyWorkphoneLink2.
     * @return PartyWorkphoneLink2
     */
    public ViewLinkImpl getPartyWorkphoneLink2() {
        return (ViewLinkImpl)findViewLink("PartyWorkphoneLink2");
    }

    /**
     * Container's getter for PartyOrganizationLink2.
     * @return PartyOrganizationLink2
     */
    public ViewLinkImpl getPartyOrganizationLink2() {
        return (ViewLinkImpl)findViewLink("PartyOrganizationLink2");
    }


    /**
     * Container's getter for SiteAddressView1.
     * @return SiteAddressView1
     */
    public ViewObjectImpl getSiteAddressView1() {
        return (ViewObjectImpl)findViewObject("SiteAddressView1");
    }

    /**
     * Container's getter for PartySiteLink1.
     * @return PartySiteLink1
     */
    public ViewLinkImpl getPartySiteLink1() {
        return (ViewLinkImpl)findViewLink("PartySiteLink1");
    }

    /**
     * Container's getter for PartyClassificationView1.
     * @return PartyClassificationView1
     */
    public ViewObjectImpl getPartyClassificationView1() {
        return (ViewObjectImpl)findViewObject("PartyClassificationView1");
    }

    /**
     * Container's getter for PartyPartyClassificationLink1.
     * @return PartyPartyClassificationLink1
     */
    public ViewLinkImpl getPartyPartyClassificationLink1() {
        return (ViewLinkImpl)findViewLink("PartyPartyClassificationLink1");
    }

    /**
     * Container's getter for PhoneView3.
     * @return PhoneView3
     */
    public ViewObjectImpl getPhoneView3() {
        return (ViewObjectImpl)findViewObject("PhoneView3");
    }

    /**
     * Container's getter for ContactMethodView1.
     * @return ContactMethodView1
     */
    public ViewObjectImpl getContactMethodView1() {
        return (ViewObjectImpl)findViewObject("ContactMethodView1");
    }

    /**
     * Container's getter for ContactMethodPartyLink1.
     * @return ContactMethodPartyLink1
     */
    public ViewLinkImpl getContactMethodPartyLink1() {
        return (ViewLinkImpl)findViewLink("ContactMethodPartyLink1");
    }
}
